from typing import Protocol


class ProviderContract(Protocol):
    provider_key: str

    def oauth_start(self, request): ...
    def oauth_callback(self, request): ...
    def refresh(self, request): ...
    def disconnect(self, request): ...
    def webhook_ingress(self, request): ...
    def apply_outbound_actions(self, connection_id: str, actions: list[dict]) -> dict: ...
